import type { SiteContent } from './types';

export const siteVi: SiteContent = {
  brand: {
    name: 'xfein',
    tagline: 'xfein · Game & Design Studio',
  },
  nav: {
    home: 'Trang chủ',
    store: 'Cửa hàng',
  },
  hero: {
    eyebrow: 'xfein · Game & Design Studio',
    headlineLine1: 'Nạp game & thiết kế',
    headlineGradient: 'tất cả tại một nơi',
    sub: 'Nạp chính ngạch Roblox, Liên Quân, Free Fire, Play Together, LoL, Valorant, FIFA, Genshin — kết hợp dịch vụ thiết kế logo, banner, thumbnail và YouTube. Tất cả tại xfein.',
    primaryCta: 'Vào cửa hàng',
    secondaryCta: 'Tra cứu đơn',
    badges: [
      'Kênh chính ngạch',
      'Nhận trong vài phút',
      'Designer riêng 1-1',
    ],
    stats: [
      { value: '10K+', label: 'Đơn đã giao' },
      { value: '99%', label: 'Giao đúng hạn' },
      { value: '4.9★', label: 'Đánh giá khách hàng' },
    ],
  },
  gameShowcase: {
    eyebrow: 'NẠP GAME',
    heading: 'Top game, kênh chính ngạch',
    sub: 'Bảy tựa game phổ biến, tất cả qua đối tác được uỷ quyền — giá minh bạch, hỗ trợ truy vết.',
    seeAll: 'Xem tất cả game',
  },
  designServices: {
    eyebrow: 'DỊCH VỤ THIẾT KẾ',
    heading: 'Thiết kế chuẩn designer',
    sub: 'Designer cấp cao, làm việc 1-1. Từ logo, banner, thumbnail tới full bộ kit YouTube.',
    items: [
      {
        key: 'logo',
        title: 'Thiết kế logo',
        desc: 'Logo thương hiệu riêng, kèm file nguồn AI/SVG và 2 lượt chỉnh sửa.',
        fromPrice: 690000,
        currency: '₫',
        cta: 'Từ',
      },
      {
        key: 'shop-banner',
        title: 'Banner shop',
        desc: 'Banner gian hàng tối ưu cho Shopee, TikTok Shop và Lazada.',
        fromPrice: 290000,
        currency: '₫',
        cta: 'Từ',
      },
      {
        key: 'thumbnail',
        title: 'Thumbnail',
        desc: 'Thumbnail YouTube và TikTok tỉ lệ click cao, tối ưu mobile.',
        fromPrice: 99000,
        currency: '₫',
        cta: 'Từ',
      },
      {
        key: 'display-banner',
        title: 'Display banner',
        desc: 'Banner web cho Google Ads, Meta Ads và landing page.',
        fromPrice: 199000,
        currency: '₫',
        cta: 'Từ',
      },
      {
        key: 'youtube-banner',
        title: 'Banner YouTube',
        desc: 'Channel art, avatar và watermark — full bộ đồng nhất thương hiệu.',
        fromPrice: 249000,
        currency: '₫',
        cta: 'Từ',
      },
      {
        key: 'icons',
        title: 'Bộ icon',
        desc: 'Bộ icon riêng theo brand, SVG + PNG, có cả light & dark.',
        fromPrice: 390000,
        currency: '₫',
        cta: 'Từ',
      },
    ],
    seeAll: 'Xem tất cả dịch vụ thiết kế',
  },
  showcase: {
    eyebrow: 'KHÁM PHÁ',
    heading: 'Chọn bên trái, xem trực tiếp bên phải',
    sub: 'Bảy tựa game cộng sáu dịch vụ thiết kế, tất cả trong một bảng. Dùng phím ← → để duyệt nhanh.',
    gamesLabel: 'Game',
    designLabel: 'Thiết kế',
    autoplayPlay: 'Tiếp tục tự chạy',
    autoplayPause: 'Tạm dừng tự chạy',
    prevLabel: 'Trước',
    nextLabel: 'Sau',
    highlightsLabel: 'Điểm nổi bật',
    seeAll: 'Mở cửa hàng đầy đủ',
  },
  serviceCommitment: {
    eyebrow: 'CAM KẾT DỊCH VỤ',
    heading: 'Lời hứa của chúng tôi',
    sub: 'Quy trình rõ ràng, trạng thái đơn minh bạch và lịch sử hỗ trợ truy vết được đầy đủ.',
    items: [
      {
        icon: 'shield-check',
        title: 'Kênh chính ngạch',
        desc: 'Mọi đơn nạp đều đi qua Garena, HoYoverse và các đối tác uỷ quyền — an toàn và đáng tin cậy.',
      },
      {
        icon: 'activity',
        title: 'Theo dõi thời gian thực',
        desc: 'Mọi bước từ thanh toán tới khi nhận đều hiển thị. Có vướng mắc, hỗ trợ trả lời trong vài phút.',
      },
      {
        icon: 'headphones',
        title: 'Designer riêng',
        desc: 'Làm việc 1-1 với designer, hai lượt chỉnh sửa miễn phí và bàn giao 100% file gốc.',
      },
    ],
  },
  howItWorks: {
    eyebrow: 'QUY TRÌNH',
    heading: 'Ba bước đơn giản',
    sub: 'Từ nạp game tới thiết kế, toàn bộ luồng đều online và truy vết được.',
    steps: [
      {
        num: '01',
        title: 'Chọn dịch vụ',
        desc: 'Duyệt mọi gói game và dịch vụ thiết kế trong cửa hàng, chọn gói phù hợp.',
      },
      {
        num: '02',
        title: 'Thanh toán an toàn',
        desc: 'Hỗ trợ Momo, ZaloPay, thẻ ngân hàng, Apple Pay và thẻ tín dụng quốc tế — đều mã hoá.',
      },
      {
        num: '03',
        title: 'Nhận hàng',
        desc: 'Nạp game về trong vài phút. File thiết kế bàn giao đúng hạn theo gói đã chọn.',
      },
    ],
  },
  featured: {
    eyebrow: 'PHỔ BIẾN',
    heading: 'Gói được yêu thích nhất',
    sub: 'Những gói game thủ và brand đặt nhiều nhất. Ổn định, nhất quán, có hỗ trợ.',
    seeAll: 'Mở cửa hàng đầy đủ',
  },
  faq: {
    eyebrow: 'CÂU HỎI THƯỜNG GẶP',
    heading: 'Câu hỏi thường gặp',
    sub: 'Trả lời cho những câu chúng tôi nhận được nhiều nhất.',
    items: [
      {
        q: 'Nạp game bao lâu thì có?',
        a: 'Đa số đơn về trong 1–10 phút. Một số gói sự kiện có thể tới 24 giờ trong các đợt cao điểm.',
      },
      {
        q: 'Có cần đưa mật khẩu game không?',
        a: 'Không. Chỉ cần ID người chơi hoặc tên trong game. Mật khẩu của bạn không bao giờ rời khỏi máy bạn.',
      },
      {
        q: 'Đơn thiết kế mất bao lâu?',
        a: 'Thumbnail và banner đơn lẻ: trong ngày. Logo và bộ icon: 3–5 ngày. Dự án lớn hơn: lịch trình riêng.',
      },
      {
        q: 'Hỗ trợ những hình thức thanh toán nào?',
        a: 'Momo, ZaloPay, VNPAY, Apple Pay, UnionPay và các thẻ tín dụng quốc tế chính.',
      },
      {
        q: 'Nếu nạp lỗi hoặc không ưng thiết kế thì sao?',
        a: 'Đơn nạp lỗi hoàn tiền 100%. Đơn thiết kế kèm 2 lượt chỉnh sửa miễn phí, nếu vẫn không vừa ý sẽ hoàn tiền theo tỉ lệ.',
      },
      {
        q: 'Có xuất hoá đơn được không?',
        a: 'Có. Mọi đơn đều có thể yêu cầu hoá đơn VAT, sẽ được phát hành trong 24 giờ sau khi đơn hoàn tất.',
      },
    ],
  },
  ctaBanner: {
    heading: 'Sẵn sàng bắt đầu?',
    sub: 'Nạp game trong vài phút. File thiết kế đúng hạn. xfein giúp mọi việc đơn giản hơn.',
    cta: 'Vào cửa hàng',
  },
  footer: {
    tagline: 'Nạp game + thiết kế hình ảnh — một studio, một lần thanh toán.',
    columns: [
      {
        title: 'Sản phẩm',
        links: [
          { label: 'Cửa hàng', href: '/store' },
          { label: 'Nạp game', href: '/store?cat=games' },
          { label: 'Dịch vụ thiết kế', href: '/store?cat=design' },
        ],
      },
      {
        title: 'Hỗ trợ',
        links: [
          { label: 'Trung tâm trợ giúp', href: '/help' },
          { label: 'Liên hệ', href: '/contact' },
          { label: 'Tra cứu đơn', href: '/orders' },
        ],
      },
      {
        title: 'Pháp lý',
        links: [
          { label: 'Điều khoản dịch vụ', href: '/terms' },
          { label: 'Bảo mật', href: '/privacy' },
          { label: 'Chính sách hoàn tiền', href: '/refund' },
        ],
      },
    ],
    copyright: '© 2026 xfein. Đã đăng ký bản quyền.',
  },
  store: {
    badgeNew: 'Mới',
    badgePopular: 'Hot',
    badgeSale: 'Giảm',
    fromPrefix: 'Từ',
    perOrder: '/ đơn',
    primaryCta: 'Mua ngay',
    detailsCta: 'Xem chi tiết',
    bannerEyebrow: 'CỬA HÀNG xfein',
    bannerHeading: 'Game + thiết kế, một nơi',
    bannerSub: 'Bảy game nạp top kết hợp sáu dịch vụ thiết kế chuyên nghiệp. Tất cả tại đây.',
    categoryAll: 'Tất cả',
    categoryGames: 'Nạp game',
    categoryDesign: 'Thiết kế',
    sortLabel: 'Sắp xếp',
    sortNewest: 'Mới nhất',
    sortPopular: 'Phổ biến',
    sortPriceAsc: 'Giá ↑',
    sortPriceDesc: 'Giá ↓',
    backToStore: 'Về cửa hàng',
    pickPackage: 'Chọn gói',
    total: 'Tổng',
    highlightsLabel: 'Điểm nổi bật',
    aboutHeading: 'Về sản phẩm này',
    relatedHeading: 'Có thể bạn cũng thích',
    moreFromBrand: 'Thêm từ {brand}',
    trustGameChannel: 'Kênh chính ngạch',
    trustGameDelivery: 'Nhận trong vài phút',
    trustGameSuccess: 'Tỉ lệ thành công 99%',
    trustDesignSource: 'Có file gốc',
    trustDesignDelivery: 'Đúng hạn',
    trustDesignRevisions: '2 lần chỉnh sửa miễn phí',
  },
};
